/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: video_object_detection.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "video_object_detection.pb-c.h"
void   vod__detection__init
                     (VOD__Detection         *message)
{
  static const VOD__Detection init_value = VOD__DETECTION__INIT;
  *message = init_value;
}
size_t vod__detection__get_packed_size
                     (const VOD__Detection *message)
{
  assert(message->base.descriptor == &vod__detection__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t vod__detection__pack
                     (const VOD__Detection *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &vod__detection__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t vod__detection__pack_to_buffer
                     (const VOD__Detection *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &vod__detection__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
VOD__Detection *
       vod__detection__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (VOD__Detection *)
     protobuf_c_message_unpack (&vod__detection__descriptor,
                                allocator, len, data);
}
void   vod__detection__free_unpacked
                     (VOD__Detection *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &vod__detection__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   vod__scene__init
                     (VOD__Scene         *message)
{
  static const VOD__Scene init_value = VOD__SCENE__INIT;
  *message = init_value;
}
size_t vod__scene__get_packed_size
                     (const VOD__Scene *message)
{
  assert(message->base.descriptor == &vod__scene__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t vod__scene__pack
                     (const VOD__Scene *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &vod__scene__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t vod__scene__pack_to_buffer
                     (const VOD__Scene *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &vod__scene__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
VOD__Scene *
       vod__scene__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (VOD__Scene *)
     protobuf_c_message_unpack (&vod__scene__descriptor,
                                allocator, len, data);
}
void   vod__scene__free_unpacked
                     (VOD__Scene *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &vod__scene__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   vod__object_class__init
                     (VOD__ObjectClass         *message)
{
  static const VOD__ObjectClass init_value = VOD__OBJECT_CLASS__INIT;
  *message = init_value;
}
size_t vod__object_class__get_packed_size
                     (const VOD__ObjectClass *message)
{
  assert(message->base.descriptor == &vod__object_class__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t vod__object_class__pack
                     (const VOD__ObjectClass *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &vod__object_class__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t vod__object_class__pack_to_buffer
                     (const VOD__ObjectClass *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &vod__object_class__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
VOD__ObjectClass *
       vod__object_class__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (VOD__ObjectClass *)
     protobuf_c_message_unpack (&vod__object_class__descriptor,
                                allocator, len, data);
}
void   vod__object_class__free_unpacked
                     (VOD__ObjectClass *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &vod__object_class__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   vod__detector_information__init
                     (VOD__DetectorInformation         *message)
{
  static const VOD__DetectorInformation init_value = VOD__DETECTOR_INFORMATION__INIT;
  *message = init_value;
}
size_t vod__detector_information__get_packed_size
                     (const VOD__DetectorInformation *message)
{
  assert(message->base.descriptor == &vod__detector_information__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t vod__detector_information__pack
                     (const VOD__DetectorInformation *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &vod__detector_information__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t vod__detector_information__pack_to_buffer
                     (const VOD__DetectorInformation *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &vod__detector_information__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
VOD__DetectorInformation *
       vod__detector_information__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (VOD__DetectorInformation *)
     protobuf_c_message_unpack (&vod__detector_information__descriptor,
                                allocator, len, data);
}
void   vod__detector_information__free_unpacked
                     (VOD__DetectorInformation *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &vod__detector_information__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor vod__detection__field_descriptors[7] =
{
  {
    "left",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(VOD__Detection, left),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "top",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(VOD__Detection, top),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "right",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(VOD__Detection, right),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bottom",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(VOD__Detection, bottom),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(VOD__Detection, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "det_class",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(VOD__Detection, det_class),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "score",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(VOD__Detection, score),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned vod__detection__field_indices_by_name[] = {
  3,   /* field[3] = bottom */
  5,   /* field[5] = det_class */
  4,   /* field[4] = id */
  0,   /* field[0] = left */
  2,   /* field[2] = right */
  6,   /* field[6] = score */
  1,   /* field[1] = top */
};
static const ProtobufCIntRange vod__detection__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor vod__detection__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "VOD.Detection",
  "Detection",
  "VOD__Detection",
  "VOD",
  sizeof(VOD__Detection),
  7,
  vod__detection__field_descriptors,
  vod__detection__field_indices_by_name,
  1,  vod__detection__number_ranges,
  (ProtobufCMessageInit) vod__detection__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor vod__scene__field_descriptors[2] =
{
  {
    "timestamp",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(VOD__Scene, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "detections",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(VOD__Scene, n_detections),
    offsetof(VOD__Scene, detections),
    &vod__detection__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned vod__scene__field_indices_by_name[] = {
  1,   /* field[1] = detections */
  0,   /* field[0] = timestamp */
};
static const ProtobufCIntRange vod__scene__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor vod__scene__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "VOD.Scene",
  "Scene",
  "VOD__Scene",
  "VOD",
  sizeof(VOD__Scene),
  2,
  vod__scene__field_descriptors,
  vod__scene__field_indices_by_name,
  1,  vod__scene__number_ranges,
  (ProtobufCMessageInit) vod__scene__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor vod__object_class__field_descriptors[2] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(VOD__ObjectClass, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(VOD__ObjectClass, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned vod__object_class__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = name */
};
static const ProtobufCIntRange vod__object_class__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor vod__object_class__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "VOD.ObjectClass",
  "ObjectClass",
  "VOD__ObjectClass",
  "VOD",
  sizeof(VOD__ObjectClass),
  2,
  vod__object_class__field_descriptors,
  vod__object_class__field_indices_by_name,
  1,  vod__object_class__number_ranges,
  (ProtobufCMessageInit) vod__object_class__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor vod__detector_information__field_descriptors[1] =
{
  {
    "classes",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(VOD__DetectorInformation, n_classes),
    offsetof(VOD__DetectorInformation, classes),
    &vod__object_class__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned vod__detector_information__field_indices_by_name[] = {
  0,   /* field[0] = classes */
};
static const ProtobufCIntRange vod__detector_information__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor vod__detector_information__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "VOD.DetectorInformation",
  "DetectorInformation",
  "VOD__DetectorInformation",
  "VOD",
  sizeof(VOD__DetectorInformation),
  1,
  vod__detector_information__field_descriptors,
  vod__detector_information__field_indices_by_name,
  1,  vod__detector_information__number_ranges,
  (ProtobufCMessageInit) vod__detector_information__init,
  NULL,NULL,NULL    /* reserved[123] */
};
